### ISSUE TITLE
No data on multiple locations

### ISSUE THREAD

**Issue by jungernichten** [HKUST-VISLab/vismooc-data-server#4]
@chenzhutian 
No data on:
calendar view of video heat map
video seek graphs
video event stack chart
Forum Sentiment Analysis

===log===
2017-06-30 02:22:58,703-vismooc-INFO-Insert data to DB
spend time:0:21:19.563241
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    main()
  File "main.py", line 70, in main
    app(first_time=True)
  File "main.py", line 58, in app
    timer = Timer(seconds_to_tmr_1_am(), app)
  File "main.py", line 28, in seconds_to_tmr_1_am
    minute=0, second=0, microsecond=0)
ValueError: day is out of range for month

**Comment by chenzhutian** [comment]
Thanks for your report!
